### ISSUE TITLE
Size of some screens

### ISSUE THREAD

**Issue by nvillano80** [rjhunjhunwala/Orbital#1]
Although the game fits my small mac screen, the instructions and title screen do not scale down with the window.

**Comment by rjhunjhunwala** [comment]
This issue has been received and I am working on a fix thanks for reporing

**Comment by rjhunjhunwala** [comment]
A temporary fix has been uploaded. It will help better present the menus on smaller screens, however I am unable to test this functionality please report if the fix worked.
<marquee>Thanks</marquee>
